### ISSUE TITLE
Behavior discrepancy with RxJS of()

### ISSUE THREAD

**Issue by loreanvictor** [Andarist/callbag-of#1]
It appears that currently `callbag-of` only emits its value(s) to _the first subscriber_ only. I personally find this rather counter-intuitive, and also not in sync with RxJS `of()`.

[playground](https://stackblitz.com/edit/callbag-of-discrepancy?file=index.ts)

**Comment by Andarist** [comment]
The easiest way to fix this would be to make a copy of `values` at [this line](https://github.com/Andarist/callbag-of/blob/2c7c323f8bdf0eccd867ada250828bd375688886/src/index.js#L4) and consume that in the rest of the implementation.

Would you like to provide a fixing PR with a new test added to cover for this?

**Comment by loreanvictor** [comment]
sure thing!

**Comment by Andarist** [comment]
Fixed by https://github.com/Andarist/callbag-of/pull/2
